# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-06 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.CharField(max_length=200)),
                ('account_firstName', models.CharField(max_length=200)),
                ('account_lastName', models.CharField(max_length=200)),
                ('account_password', models.CharField(max_length=200)),
            ],
        ),
    ]
