# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-08 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_email', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=200)),
                ('message_text', models.CharField(max_length=500)),
            ],
        ),
    ]
