# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-08 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpakers', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_email',
            field=models.EmailField(max_length=200),
        ),
    ]
