# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpakers', '0003_auto_20170609_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=200)),
                ('token', models.CharField(max_length=200)),
            ],
        ),
    ]
