# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-06-12 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backpakers', '0004_tokencode'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
